name: todo_main_app
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.0.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  connectivity_plus: ^4.0.2
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  equatable: ^2.0.5
  mockito: ^5.4.2
  flutter_bloc: ^8.1.3
  get_it: ^7.6.0
  http: ^1.1.0
  internet_connection_checker: ^1.0.0+1
  intl: ^0.18.1
  meta: ^1.9.1
  shared_preferences: ^2.2.0
  url_launcher: ^6.1.12

dev_dependencies:
  flutter_lints: ^2.0.0
  bloc_test: ^9.1.4
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
